Forum/Models/Post.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Post
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Post")]
        public string Context { get; set; }

        [Required]
        [Display(Name = "Autor")]
        public string Author { get; set; }

        [Required]
        public int TopicId { get; set; }
    
        public virtual Topic Topic { get; set; }
    }
}

Forum/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Forum.Models;

namespace Forum.Controllers
{
    public class PostsController : Controller
    {
        private PostsContext db = new PostsContext();

        //
        // GET: /Posts/

        public ActionResult Index(int TopicId)
        {
            var posts = db.Posts.Include(p => p.Topic).Where(p => p.TopicId == TopicId);
            var topic = db.Topics.Find(TopicId);
            ViewBag.TopicId = TopicId;
            ViewBag.TopicName = topic.Name;
            ViewBag.CategoryId = topic.CategoryId;
            return View(posts.ToList());
        }

        //
        // GET: /Posts/Create
        [Authorize]
        public ActionResult Create(int TopicId)
        {
            ViewBag.TopicId = TopicId;
            return View();
        }

        //
        // POST: /Posts/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(Post post, int TopicId)
        {
            if (ModelState.IsValidField("Context"))
            {
                post.Author = User.Identity.Name;
                post.TopicId = TopicId;
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index", new { TopicId = TopicId });
            }

            ViewBag.TopicId = TopicId;
            return View(post);
        }

        //
        // GET: /Posts/Edit/5
        [Authorize]
        public ActionResult Edit(int id, int TopicId)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.TopicId = TopicId;
            return View(post);
        }

        //
        // POST: /Posts/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(Post post, int TopicId)
        {
            if (ModelState.IsValidField("Context"))
            {
                post.Author = User.Identity.Name;
                post.TopicId = TopicId;
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { TopicId = TopicId });
            }
            ViewBag.TopicId = TopicId;
            return View(post);
        }

        //
        // GET: /Posts/Delete/5
        [Authorize(Roles="Admin")]
        public ActionResult Delete(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.TopicId = post.TopicId;
            return View(post);
        }

        //
        // POST: /Posts/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id, int TopicId)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index", new { TopicId = TopicId });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Forum/Views/Posts/Create.cshtml
@model Forum.Models.Post

@{
    ViewBag.Title = "Create";
}

<div class="col-xs-12 col-sm-6 col-sm-push-3">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <form class="form">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Context, htmlAttributes: new { @class = "control-label" })
                @Html.TextAreaFor(model => model.Context, new { @class = "form-control", @placeholder = "Post" })
                @Html.ValidationMessageFor(model => model.Context, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
                <a href="@Url.Action("Index", "Posts", new { TopicId = ViewBag.TopicId })" class="btn btn-default">Anuluj</a>
            </div>
        </form>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Forum/Views/Posts/Delete.cshtml
@model Forum.Models.Post

@{
    ViewBag.Title = "Delete";
}

<div class="col-xs-12 col-sm-6 col-sm-push-3">
    @using (Html.BeginForm())
    {
        <form class="form">
            @Html.AntiForgeryToken()
            <div class="form-group">
                <label>Czy na pewno chcesz usunąć element</label> "@Html.DisplayFor(model => model.Context)" <strong>?</strong>
            </div>
            <div class="form-group">
                <input type="submit" value="Usuń" class="btn btn-danger" />
                <a href="@Url.Action("Index", "Posts", new { TopicId = ViewBag.TopicId })" class="btn btn-default">Anuluj</a>
            </div>
            
        </form>
    }
</div>

Forum/Views/Posts/Edit.cshtml
@model Forum.Models.Post

@{
    ViewBag.Title = "Edit";
}

<div class="col-xs-12 col-sm-6 col-sm-push-3">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <form class="form">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Context, htmlAttributes: new { @class = "control-label" })
                @Html.TextAreaFor(model => model.Context, new { @class = "form-control", @placeholder = "Treść" })
                @Html.ValidationMessageFor(model => model.Context, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
                <a href="@Url.Action("Index", "Posts", new { TopicId = ViewBag.TopicId })" class="btn btn-default">Anuluj</a>
            </div>
        </form>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Forum/Views/Posts/Index.cshtml
@model IEnumerable<Forum.Models.Post>

@{
    ViewBag.Title = "Index";
}

<h2>
    @ViewBag.TopicName
</h2>

<div id="button-panel" class="col-xs-12">
    <a href="@Url.Action("Create", "Posts", new { TopicId = ViewBag.TopicId })" class="btn btn-link">Create New</a>
    <a href="@Url.Action("Index", "Topics", new { CategoryId = ViewBag.CategoryId })" class="btn btn-link pull-right">Back</a>
</div>
<div class="col-xs-12">
    <div class="row">
        <div class="table-responsive">
            <table class="table table-striped">
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="col-xs-2">
                                @Html.DisplayFor(modelItem => item.Author)
                            </td>
                            <td class="col-xs-8">
                                @Html.DisplayFor(modelItem => item.Context)
                            </td>
                            @if (Request.IsAuthenticated)
                            {
                                <td class="col-xs-1">
                                    @if (this.User.Identity.Name == "Admin")
                                    {
                                        <a href="@Url.Action("Delete", "Posts", new { id = item.Id, TopicId = ViewBag.TopicId })" class="btn btn-link pull-right"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                                    }
                                    @if (this.User.Identity.Name == "Admin" || this.User.Identity.Name == item.Author)
                                    {
                                        <a href="@Url.Action("Edit", "Posts", new { id = item.Id, TopicId = ViewBag.TopicId })" class="btn btn-link pull-right"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>
                                    }
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="col-xs-12">
    <a href="#button-panel" class="btn btn-link pull-right">Go top</a>
</div>