Forum/Models/Category.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Category
    {
        public Category()
        {
            this.Topics = new HashSet<Topic>();
        }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Nazwa")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Opis")]
        public string Comment { get; set; }
    
        public virtual ICollection<Topic> Topics { get; set; }
    }
}

Forum/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Forum.Models;

namespace Forum.Controllers
{
    public class CategoriesController : Controller
    {
        private CategoryContext db = new CategoryContext();

        //
        // GET: /Categories/

        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        //
        // GET: /Categories/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Categories/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        //
        // GET: /Categories/Edit/5
        [Authorize]
        public ActionResult Edit(int id = 0)
        {
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        //
        // POST: /Categories/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        //
        // GET: /Categories/Delete/5
        [Authorize]
        public ActionResult Delete(int id = 0)
        {
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        //
        // POST: /Categories/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Forum/Views/Categories/Create.cshtml
@model Forum.Models.Category

@{
    ViewBag.Title = "Create";
}

<div class="col-xs-12 col-sm-6 col-sm-push-3">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Nazwa" })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Comment, new { @class = "form-control", @placeholder = "Komentarz" })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
                <a href="@Url.Action("Index", "Categories")" class="btn btn-default">Na główną</a>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Forum/Views/Categories/Delete.cshtml
@model Forum.Models.Category

@{
    ViewBag.Title = "Delete";
}

<div class="col-xs-12 col-sm-6 col-sm-push-3">
    @using (Html.BeginForm())
    {
        <div class="form">
            @Html.AntiForgeryToken()
            <div class="form-group">
                <label>Czy na pewno chcesz usunąć element</label> "@Html.DisplayFor(model => model.Name)" <strong>?</strong>
            </div>
            <div class="form-group">
                <input type="submit" value="Usuń" class="btn btn-danger" />
                <a href="@Url.Action("Index", "Categories")" class="btn btn-default">Anuluj</a>
            </div>
        </div>
    }
</div>

Forum/Views/Categories/Edit.cshtml
@model Forum.Models.Category

@{
    ViewBag.Title = "Edit";
}

<div class="col-xs-12 col-sm-6 col-sm-push-3">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)

        <form class="form">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Nazwa" })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Comment, new { @class = "form-control", @placeholder = "Komentarz" })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
                <a href="@Url.Action("Index", "Categories")" class="btn btn-default">Na główną</a>
            </div>
        </form>
    }
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Forum/Views/Categories/Index.cshtml
@model IEnumerable<Forum.Models.Category>

@{
    ViewBag.Title = "Index";
}

@foreach (var item in Model)
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-9">
                    <a href="@Url.Action("Index", "Topics", new { CategoryId = item.Id })" class="btn btn-link">
                        <div class="lead">
                            @Html.DisplayFor(modelItem => item.Name)
                        </div>
                    </a>
                </div>
                <div class="col-xs-3 pull-right">
                    @if (Request.IsAuthenticated && this.User.Identity.Name == "Admin")
                    {
                        <a href="@Url.Action("Delete", "Categories", new {id = item.Id})" class="btn btn-link pull-right">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                        <a href="@Url.Action("Edit", "Categories", new {id = item.Id})" class="btn btn-link pull-right">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>
                    }
                </div>
            </div>
        </div>
        <div class="panel-body">
            <small>
                @Html.DisplayFor(modelItem => item.Comment)
            </small>
        </div>
    </div>
}
@if (Request.IsAuthenticated && this.User.Identity.Name == "Admin")
{
    <div class="col-xs-12">
        @Html.ActionLink("Stwórz forum", "Create")
    </div>
}